module.exports = {
  ROLES: {
    SUPER_ADMIN: 'super_admin',
    ADMIN: 'admin',
    SALES: 'sales',
    FINANCE: 'finance',
    SERVICE_MANAGER: 'service_manager',
    TRAINER: 'trainer',
    RECEPTION: 'reception',
  },
  LEAD_STAGES: [
    'New',
    'Assigned',
    'Follow up',
    'Hot lead',
    'Test ride done',
    'Negotiation',
    'Booked',
    'Lost',
  ],
  LEAD_SOURCES: [
    'Website',
    'Product Enquiry',
    'WhatsApp',
    'Walk-in',
    'Referral',
    'Meta Ads',
    'Google Ads',
    'Digital',
    'Field Activity',
    'Database',
    'Exchange',
    'Finance Partner',
    'Event/BTL',
    'Organic',
  ],
  INTERESTS: [
    'New motorcycle',
    'Chetak Electric',
    'Three-wheeler / commercial',
    'Finance & EMI',
    'Service booking',
    'Exchange valuation',
    'Driving training',
    'Licence assistance',
  ],
  FINANCE_STATUSES: [
    'Login Pending',
    'Approved',
    'Rejected',
    'Disbursed',
    'Documentation Pending',
  ],
  REVIEW_STATUSES: ['Open', 'In Progress', 'Closed', 'Hold'],
  BRANCH_NAMES: ['Muzaffarpur', 'Sheohar', 'Paroo', 'Karza'],
  TEST_RIDE_SLOTS: ['10:00 AM', '12:00 PM', '3:00 PM', '5:00 PM'],
  TEST_RIDE_MODELS: [
    'Pulsar NS200',
    'Pulsar N250',
    'Dominar 400',
    'Avenger 220',
    'Platina 110',
    'Chetak Premium',
    'Bajaj RE',
  ],
  PRODUCT_CATEGORIES: ['motorcycle', 'electric', 'three_wheeler'],
  HEALTH: {
    GAP: 'Gap',
    ACTIVE: 'Active',
    ON_TRACK: 'On Track',
    PENDING: 'Pending',
  },
};
